import { ChangeDetectionStrategy, Component, computed, effect, inject, signal } from '@angular/core';
import { TranslatePipe } from '../../core/i18n/translate.pipe';
import type { InternshipDocument, InternshipPeriod, InternshipStatus } from "../../core/models/internships.models";
import { SessionService } from '../../core/session/session.service';
import { ContextualTrainingDataService } from '../../core/workspace/contextual-training-data.service';
import { WorkplaceApiService } from '../../core/workplace/workplace-api.service';
import type { CohortLearnerDto, WorkplacePeriodDto } from '../../core/workplace/workplace.models';
import { ProgressBarComponent } from '../../shared/ui/progress-bar.component';
import { CreateInternshipDrawerComponent, type CreateInternshipPeriodPayload } from './create-internship-drawer/create-internship-drawer.component';
@Component({selector:'app-internships',imports:[TranslatePipe,ProgressBarComponent,CreateInternshipDrawerComponent],templateUrl:'./internships.component.html',changeDetection:ChangeDetectionStrategy.OnPush})
export class InternshipsComponent {
  readonly sessionService=inject(SessionService); readonly contextData=inject(ContextualTrainingDataService); private readonly api=inject(WorkplaceApiService);
  readonly drawerOpen=signal(false); readonly remotePeriods=signal<InternshipPeriod[]|null>(null); readonly remoteLearners=signal<CohortLearnerDto[]>([]); readonly loading=signal(false);
  constructor(){effect(()=>{const apiId=this.contextData.cohort()?.apiId;if(apiId)void this.load(apiId);else this.remotePeriods.set([]);});}
  readonly periods=computed(()=>{const all=this.remotePeriods()??this.contextData.internships();const role=this.sessionService.role();if(role==='stagiaire'){const studentId=this.sessionService.session()?.studentId??'s1';return all.filter(x=>x.studentId===studentId);}if(role==='formateur')return all.filter(x=>x.trainerVisible);return all;});
  readonly totals=computed(()=>{const p=this.periods(),planned=p.reduce((t,x)=>t+x.plannedHours,0),completed=p.reduce((t,x)=>t+x.completedHours,0);return{planned,completed,remaining:Math.max(0,planned-completed),incomplete:p.filter(x=>x.status==='incomplete').length};});
  readonly canCreate=computed(()=>['direction','secretariat'].includes(this.sessionService.role()));
  titleKey(){return this.sessionService.role()==='stagiaire'?'internships.studentTitle':this.sessionService.role()==='formateur'?'internships.trainerTitle':'internships.title';}
  subtitleKey(){return this.sessionService.role()==='stagiaire'?'internships.studentSubtitle':this.sessionService.role()==='formateur'?'internships.trainerSubtitle':'internships.subtitle';}
  openDrawer(){this.drawerOpen.set(true);} closeDrawer(){this.drawerOpen.set(false);}
  async addPeriod(payload:CreateInternshipPeriodPayload){const cohort=this.contextData.cohort();if(!cohort?.apiId){return;}const learner=this.remoteLearners().find(x=>x.externalKey===payload.studentId)||this.remoteLearners().find(x=>`${x.firstName} ${x.lastName}`===payload.studentName);if(!learner)return;try{await this.api.createPeriod({enrollmentId:learner.enrollmentId,periodTypeCode:'CCP1',company:payload.company,city:payload.city,tutorName:payload.tutor,tutorEmail:payload.tutorEmail,tutorPhone:payload.tutorPhone,startDate:payload.startDate,endDate:payload.endDate,plannedHours:payload.plannedHours,agreementReceived:payload.agreementReceived,notes:payload.notes});await this.load(cohort.apiId);}catch{ /* global API error interceptor owns feedback; current remote data stays unchanged */ }}
  progress(p:InternshipPeriod){return p.plannedHours?Math.round((p.completedHours/p.plannedHours)*100):0;} remaining(p:InternshipPeriod){return Math.max(0,p.plannedHours-p.completedHours);} statusClass(s:InternshipStatus){switch(s){case'completed':return'bg-[#d8f8df] text-[#18a547]';case'incomplete':return'bg-[#ffe1df] text-[#f22b2b]';case'inProgress':return'bg-[#fff0c9] text-[#8b5e00]';default:return'bg-[#e5f2ff] text-[#2a64a2]';}} documentClass(d:InternshipDocument){return d.status==='validated'?'bg-[#d8f8df] text-[#18a547]':d.status==='missing'?'bg-[#ffe1df] text-[#f22b2b]':'bg-[#e5f2ff] text-[#245c97]';}
  private async load(cohortId:string){this.loading.set(true);try{const [periods,learners]=await Promise.all([this.api.getPeriods(cohortId),this.api.getLearners(cohortId)]);this.remoteLearners.set(learners);this.remotePeriods.set(periods.map(x=>this.toLegacy(x,learners)));}catch{this.remotePeriods.set([]);}finally{this.loading.set(false);}}
  private toLegacy(x:WorkplacePeriodDto,learners:CohortLearnerDto[]):InternshipPeriod{const learner=learners.find(l=>l.enrollmentId===x.enrollmentId);return{id:x.id,studentId:learner?.externalKey??x.enrollmentId,studentName:x.learnerDisplayName||learner?.displayName||'',company:x.company,city:x.city,tutor:x.tutorName,startDate:this.fr(x.startDate),endDate:this.fr(x.endDate),plannedHours:x.plannedHours,completedHours:x.completedHours,status:x.status==='cancelled'?'incomplete':x.status,trainerVisible:x.trainerVisible,activities:x.activities.map(a=>({labelKey:a.labelKey||a.title,status:a.status==='done'?'done':'pending'})),tutorObservationKey:x.tutorObservation||'internships.observations.notStarted',documents:x.documents.map(d=>({labelKey:d.labelKey||d.title,status:d.status}))};}
  private fr(v:string){const [y,m,d]=v.split('-');return y&&m&&d?`${d}/${m}/${y}`:v;}
}
