import type { StudentStatus } from "../models/app.models";

export interface StudentDirectoryItem {
  id: string;
  firstName: string;
  lastName: string;
  promotionId: string;
  promotionName: string;
  progress: number;
  completedHours: number;
  catchupHours: number;
  preparedSheets: number;
  presentedSheets: number;
  validatedSheets: number;
  status: StudentStatus;
}

export const STUDENT_DIRECTORY: StudentDirectoryItem[] = [
  {
    id: "s1",
    firstName: "Sam",
    lastName: "Fokam",
    promotionId: "p1",
    promotionName: "TP ECSR 2026–2027",
    progress: 72,
    completedHours: 684,
    catchupHours: 4,
    preparedSheets: 37,
    presentedSheets: 24,
    validatedSheets: 32,
    status: "good",
  },
  {
    id: "s2",
    firstName: "Julie",
    lastName: "Moreau",
    promotionId: "p1",
    promotionName: "TP ECSR 2026–2027",
    progress: 61,
    completedHours: 555,
    catchupHours: 14,
    preparedSheets: 32,
    presentedSheets: 22,
    validatedSheets: 19,
    status: "late",
  },
  {
    id: "s3",
    firstName: "Marc",
    lastName: "Girard",
    promotionId: "p1",
    promotionName: "TP ECSR 2026–2027",
    progress: 78,
    completedHours: 710,
    catchupHours: 0,
    preparedSheets: 41,
    presentedSheets: 28,
    validatedSheets: 24,
    status: "good",
  },
  {
    id: "s4",
    firstName: "Léa",
    lastName: "Perrin",
    promotionId: "p1",
    promotionName: "TP ECSR 2026–2027",
    progress: 55,
    completedHours: 501,
    catchupHours: 12,
    preparedSheets: 29,
    presentedSheets: 20,
    validatedSheets: 17,
    status: "warning",
  },
  {
    id: "s5",
    firstName: "Karim",
    lastName: "Benali",
    promotionId: "p1",
    promotionName: "TP ECSR 2026–2027",
    progress: 84,
    completedHours: 764,
    catchupHours: 2,
    preparedSheets: 44,
    presentedSheets: 30,
    validatedSheets: 26,
    status: "good",
  },
  {
    id: "s6",
    firstName: "Nadia",
    lastName: "Chevalier",
    promotionId: "p1",
    promotionName: "TP ECSR 2026–2027",
    progress: 66,
    completedHours: 601,
    catchupHours: 7,
    preparedSheets: 34,
    presentedSheets: 23,
    validatedSheets: 20,
    status: "good",
  },
  {
    id: "s7",
    firstName: "Thomas",
    lastName: "Roussel",
    promotionId: "p1",
    promotionName: "TP ECSR 2026–2027",
    progress: 47,
    completedHours: 428,
    catchupHours: 18,
    preparedSheets: 24,
    presentedSheets: 16,
    validatedSheets: 14,
    status: "late",
  },
  {
    id: "s8",
    firstName: "Chloé",
    lastName: "Marchand",
    promotionId: "p1",
    promotionName: "TP ECSR 2026–2027",
    progress: 91,
    completedHours: 828,
    catchupHours: 0,
    preparedSheets: 47,
    presentedSheets: 32,
    validatedSheets: 27,
    status: "good",
  },
  {
    id: "s9",
    firstName: "Mehdi",
    lastName: "Amrani",
    promotionId: "p1",
    promotionName: "TP ECSR 2026–2027",
    progress: 69,
    completedHours: 628,
    catchupHours: 3,
    preparedSheets: 36,
    presentedSheets: 24,
    validatedSheets: 21,
    status: "good",
  },
  {
    id: "s10",
    firstName: "Emma",
    lastName: "Lefèvre",
    promotionId: "p2",
    promotionName: "TP ECSR 2025–2026",
    progress: 74,
    completedHours: 673,
    catchupHours: 2,
    preparedSheets: 39,
    presentedSheets: 26,
    validatedSheets: 23,
    status: "good",
  },
  {
    id: "s11",
    firstName: "Lucas",
    lastName: "Barbier",
    promotionId: "p2",
    promotionName: "TP ECSR 2025–2026",
    progress: 58,
    completedHours: 528,
    catchupHours: 9,
    preparedSheets: 31,
    presentedSheets: 20,
    validatedSheets: 16,
    status: "warning",
  },
  {
    id: "s12",
    firstName: "Awa",
    lastName: "Diallo",
    promotionId: "p2",
    promotionName: "TP ECSR 2025–2026",
    progress: 80,
    completedHours: 728,
    catchupHours: 0,
    preparedSheets: 42,
    presentedSheets: 29,
    validatedSheets: 25,
    status: "good",
  },
  {
    id: "s13",
    firstName: "Hugo",
    lastName: "Renaud",
    promotionId: "p2",
    promotionName: "TP ECSR 2025–2026",
    progress: 63,
    completedHours: 573,
    catchupHours: 6,
    preparedSheets: 33,
    presentedSheets: 22,
    validatedSheets: 18,
    status: "warning",
  },
  {
    id: "s14",
    firstName: "Sarah",
    lastName: "Colin",
    promotionId: "p2",
    promotionName: "TP ECSR 2025–2026",
    progress: 52,
    completedHours: 473,
    catchupHours: 15,
    preparedSheets: 27,
    presentedSheets: 18,
    validatedSheets: 15,
    status: "late",
  },
  {
    id: "s15",
    firstName: "Antoine",
    lastName: "Vasseur",
    promotionId: "p2",
    promotionName: "TP ECSR 2025–2026",
    progress: 88,
    completedHours: 801,
    catchupHours: 0,
    preparedSheets: 46,
    presentedSheets: 31,
    validatedSheets: 27,
    status: "good",
  },
];
